/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author virgi
 */
public class Page_Payment extends javax.swing.JFrame {
private String e;
    /**
     * Creates new form Page_Payment
     */
    DefaultTableModel model; 
    public Page_Payment() {
        String[] judul = {"Kode Transaksi", "Tanggal Transaksi", "Nama Pasien", "Umur","Gejala", "Diagnosa", "Nama Dokter", "Kode Obat", "Nama Obat", "Kode Ruangan", "Nama Ruangan"};
        model = new DefaultTableModel(judul, 0);
        tbl_payment.setModel(model);
        tampilData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kode_pasien = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        umur_pasien = new javax.swing.JTextField();
        gejala = new javax.swing.JTextField();
        diagnosa = new javax.swing.JTextField();
        cari_pasien = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dokter_pasien = new javax.swing.JTextField();
        kode_obat = new javax.swing.JTextField();
        nama_obat = new javax.swing.JTextField();
        kode_ruang = new javax.swing.JTextField();
        nama_ruang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tgl_trans = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        cari_obat = new javax.swing.JButton();
        cari_ruangan = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_payment = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        kode_trans = new javax.swing.JTextField();
        cari_trans = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PAYMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setText("Kode Pasien");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setText("Nama pasien");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel4.setText("Umur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel5.setText("Gejala");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel6.setText("Diagnosa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));
        getContentPane().add(kode_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 91, -1));
        getContentPane().add(nama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 158, -1));
        getContentPane().add(umur_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 158, -1));
        getContentPane().add(gejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 158, -1));
        getContentPane().add(diagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 158, -1));

        cari_pasien.setText("Cari");
        cari_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_pasienActionPerformed(evt);
            }
        });
        getContentPane().add(cari_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel8.setText("Nama Dokter");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel9.setText("Kode Obat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel10.setText("Nama Obat");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel11.setText("Kode Ruangan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel12.setText("Nama Ruangan");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));
        getContentPane().add(dokter_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 158, -1));

        kode_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_obatActionPerformed(evt);
            }
        });
        getContentPane().add(kode_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 153, -1));

        nama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatActionPerformed(evt);
            }
        });
        getContentPane().add(nama_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 153, -1));
        getContentPane().add(kode_ruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 153, -1));
        getContentPane().add(nama_ruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 153, -1));

        jLabel13.setText("Tanggal periksa");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));
        getContentPane().add(tgl_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 157, -1));

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        cari_obat.setText("Cari");
        cari_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_obatActionPerformed(evt);
            }
        });
        getContentPane().add(cari_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

        cari_ruangan.setText("Cari");
        cari_ruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_ruanganActionPerformed(evt);
            }
        });
        getContentPane().add(cari_ruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        tbl_payment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_paymentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_payment);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, 156));

        jLabel7.setText("Kode Transaksi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));
        getContentPane().add(kode_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 153, -1));

        cari_trans.setText("Cari");
        cari_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_transActionPerformed(evt);
            }
        });
        getContentPane().add(cari_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Icon/Icon Payment.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Pengobatan Rumah Sakit Fakultas Teknik");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cari_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_pasienActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "SELECT * FROM data_pasien WHERE ID_Pasien";
            String sql2 = "SELECT * FROM data_lab WHERE ID_Pasien";
            try (java.sql.PreparedStatement statement = cn.prepareStatement(sql)) {
                ResultSet rs = statement.executeQuery(sql);
                if (rs.next()){
                    
                    nama_pasien.setText(rs.getString(2));
                    gejala.setText(rs.getString(4));
                    diagnosa.setText(rs.getString(5));
                    dokter_pasien.setText(rs.getString(7));
                    
                    JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        catch( SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cari_pasienActionPerformed

    private void kode_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_obatActionPerformed

    private void nama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_obatActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        new Page_CetakTransaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cetakActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        new Page_MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void cari_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_obatActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "SELECT * FROM data_obat WHERE Kode_Obat";
            try (java.sql.PreparedStatement statement = cn.prepareStatement(sql)) {
                ResultSet rs = statement.executeQuery(sql);
                if (rs.next()){
                    
                    nama_obat.setText(rs.getString(2));
                    
                    JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        catch( SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cari_obatActionPerformed

    private void cari_ruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_ruanganActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "SELECT * FROM data_rawatinap WHERE Kode_Ruang";
            try (java.sql.PreparedStatement statement = cn.prepareStatement(sql)) {
                ResultSet rs = statement.executeQuery(sql);
                if (rs.next()){
                    
                    nama_ruang.setText(rs.getString(2));
                    
                    JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        catch( SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cari_ruanganActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "insert into data_payment values(?,?,?,?,?,?,?,?,?,?,?,?)";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);

            statement.setString(1, kode_trans.getText());
            statement.setString(2, tgl_trans.getText());
            statement.setString(3, kode_pasien.getText());
            statement.setString(4, nama_pasien.getText());
            statement.setString(5, umur_pasien.getText());
            statement.setString(6, gejala.getText());
            statement.setString(7, diagnosa.getText());
            statement.setString(8, dokter_pasien.getText());
            statement.setString(9, kode_obat.getText());
            statement.setString(10, nama_obat.getText());
            statement.setString(11, kode_ruang.getText());
            statement.setString(12, nama_ruang.getText());

            statement.executeUpdate();
            tampilData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN", "informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN" + e);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "update data_payment set Tanggal_Transaksi=?, Kode_Pasien=?, Nama_Pasien=?, Umur_Pasien=?, Gejala_Pasien=?, Diagnosa_Pasien=?, Doktor_Pasien=?, Kode_Obat=?, Nama_Obat=?, Kode_Ruang=?, Nama_Ruang=? where Kode_Transaksi=?";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);

            statement.setString(1, kode_trans.getText());
            statement.setString(2, tgl_trans.getText());
            statement.setString(3, kode_pasien.getText());
            statement.setString(4, nama_pasien.getText());
            statement.setString(5, umur_pasien.getText());
            statement.setString(6, gejala.getText());
            statement.setString(7, diagnosa.getText());
            statement.setString(8, dokter_pasien.getText());
            statement.setString(9, kode_obat.getText());
            statement.setString(10, nama_obat.getText());
            statement.setString(11, kode_ruang.getText());
            statement.setString(12, nama_ruang.getText());

            statement.executeUpdate();
            tampilData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH", "informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH" + e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int baris = tbl_payment.getSelectedRow();
        String kode_trans = model.getValueAt(baris, 0).toString();
        int Data = JOptionPane.showConfirmDialog(null, "Apakah anda ingin mengapus data kode transaksi : " + kode_trans + "?", "konfirmasi", JOptionPane.YES_NO_OPTION);

        if (Data == 0) {
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
                String sql = "delete from data_payment where Kode_Transaksi ='" + kode_trans + "'";
                java.sql.PreparedStatement statement = cn.prepareStatement(sql);

                statement.executeUpdate();
                tampilData();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS", "informasi", JOptionPane.INFORMATION_MESSAGE);
                reset();

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DIHAPUS" + e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_paymentMouseClicked
        // TODO add your handling code here:
        int i = tbl_payment.getSelectedRow();

        if (i > -1) {
            kode_trans.setText(model.getValueAt(i, 0).toString());
            tgl_trans.setText(model.getValueAt(i, 1).toString());
            kode_pasien.setText(model.getValueAt(i, 2).toString());
            nama_pasien.setText(model.getValueAt(i, 3).toString());
            umur_pasien.setText(model.getValueAt(i, 4).toString());
            gejala.setText(model.getValueAt(i, 5).toString());
            diagnosa.setText(model.getValueAt(i, 6).toString());
            dokter_pasien.setText(model.getValueAt(i, 7).toString());
            kode_obat.setText(model.getValueAt(i, 8).toString());
            nama_obat.setText(model.getValueAt(i, 9).toString());
            kode_ruang.setText(model.getValueAt(i, 10).toString());
            nama_ruang.setText(model.getValueAt(i, 11).toString());
        }
    }//GEN-LAST:event_tbl_paymentMouseClicked

    private void cari_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_transActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "SELECT * FROM data_payment WHERE Kode_Transaksi";
            try (java.sql.PreparedStatement statement = cn.prepareStatement(sql)) {
                ResultSet rs = statement.executeQuery(sql);
                if (rs.next()){
                    
                    tgl_trans.setText(rs.getString(2));
                    nama_pasien.setText(rs.getString(3));
                    umur_pasien.setText(rs.getString(4));
                    gejala.setText(rs.getString(5));
                    diagnosa.setText(rs.getString(6));
                    dokter_pasien.setText(rs.getString(7));
                    kode_obat.setText(rs.getString(8));
                    nama_obat.setText(rs.getString(9));
                    kode_ruang.setText(rs.getString(10));
                    nama_ruang.setText(rs.getString(11));
                    
                    JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        catch( SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cari_transActionPerformed

    private void reset(){
        kode_trans.setText("");
        tgl_trans.setText("");
        kode_pasien.setText("");
        nama_pasien.setText("");
        umur_pasien.setText("");
        gejala.setText("");
        diagnosa.setText("");
        dokter_pasien.setText("");
        kode_obat.setText("");
        nama_obat.setText("");
        kode_ruang.setText("");
        nama_ruang.setText("");
        
    }
    private void tampilData() {
        int row = tbl_payment.getRowCount();
        for (int a = 0; a < row; a++) {
            model.removeRow(0);
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/apotek", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM payment");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12)};
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan Data GAGAL" + e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton cari_obat;
    private javax.swing.JButton cari_pasien;
    private javax.swing.JButton cari_ruangan;
    private javax.swing.JButton cari_trans;
    private javax.swing.JButton cetak;
    private javax.swing.JTextField diagnosa;
    private javax.swing.JTextField dokter_pasien;
    private javax.swing.JTextField gejala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode_obat;
    private javax.swing.JTextField kode_pasien;
    private javax.swing.JTextField kode_ruang;
    private javax.swing.JTextField kode_trans;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField nama_ruang;
    private javax.swing.JTable tbl_payment;
    private javax.swing.JTextField tgl_trans;
    private javax.swing.JTextField umur_pasien;
    // End of variables declaration//GEN-END:variables
}
