
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author virgi
 */
public class Page_Laboraturium extends javax.swing.JFrame {

    /**
     * Creates new form Page_Laboraturium
     */
    DefaultTableModel model;
    public Page_Laboraturium() {
        initComponents();
        String[] judul = {"ID Pasien", "Gejala", "Diagnosa", "Obat"};
        model = new DefaultTableModel(judul, 0);
        tbl_datalab.setModel(model);
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datalab = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        ID_Pasien = new javax.swing.JTextField();
        Gejala_Penyakit = new javax.swing.JTextField();
        Kode_Obat = new javax.swing.JTextField();
        Diagnosa_Penyakit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("HASIL DATA LABORATORIUM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jLabel2.setText("ID Pasien");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel3.setText("Gejala");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        tbl_datalab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datalab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datalabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datalab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, 122));

        jLabel4.setText("Diagnosa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel5.setText("Kode Obat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 20));

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));
        getContentPane().add(ID_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 260, -1));
        getContentPane().add(Gejala_Penyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 260, -1));
        getContentPane().add(Kode_Obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 260, -1));
        getContentPane().add(Diagnosa_Penyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 260, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Rumah Sakit Fakultas Teknik Universitas Indonesia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Icon/Icon Lab.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 90, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "insert into data_lab values(?,?,?,?)";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);

            statement.setString(1, ID_Pasien.getText());
            statement.setString(2, Gejala_Penyakit.getText());
            statement.setString(3, Diagnosa_Penyakit.getText());
            statement.setString(4, Kode_Obat.getText());

            statement.executeUpdate();
            tampilData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN", "informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN" + e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "update data_lab set Gejala_Penyakit=?, Diagnosa_Penyakit=?, Kode_Obat=? where ID_Pasien=?";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);

            statement.setString(1, Gejala_Penyakit.getText());
            statement.setString(2, Diagnosa_Penyakit.getText());
            statement.setString(3, Kode_Obat.getText());
            statement.setString(4, ID_Pasien.getText());

            statement.executeUpdate();
            tampilData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH", "informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH" + e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int baris = tbl_datalab.getSelectedRow();
        String kode_pasien = model.getValueAt(baris, 0).toString();
        int Data = JOptionPane.showConfirmDialog(null, "Apakah anda ingin mengapus data laboratorium pasien : " + kode_pasien + "?", "konfirmasi", JOptionPane.YES_NO_OPTION);

        if (Data == 0) {
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
                String sql = "delete from data_lab where ID_Pasien ='" + kode_pasien + "'";
                java.sql.PreparedStatement statement = cn.prepareStatement(sql);

                statement.executeUpdate();
                tampilData();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS", "informasi", JOptionPane.INFORMATION_MESSAGE);
                reset();

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DIHAPUS" + e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_datalabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datalabMouseClicked
        // TODO add your handling code here:
        int i = tbl_datalab.getSelectedRow();

        if (i > -1) {
            ID_Pasien.setText(model.getValueAt(i, 0).toString());
            Gejala_Penyakit.setText(model.getValueAt(i, 1).toString());
            Diagnosa_Penyakit.setText(model.getValueAt(i, 2).toString());
            Kode_Obat.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_tbl_datalabMouseClicked

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        new Page_MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    
    private void reset(){
        ID_Pasien.setText("");
        Gejala_Penyakit.setText("");
        Diagnosa_Penyakit.setText("");
        Kode_Obat.setText("");
    }
        
    private void tampilData() {
        int row = tbl_datalab.getRowCount();
        for (int a = 0; a < row; a++) {
            model.removeRow(0);
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM data_lab");
            while (rs.next()) {
                String data[] = {rs.getString("ID_Pasien"), rs.getString("Gejala_Penyakit"), rs.getString("Diagnosa_Penyakit"), rs.getString("Kode_Obat")};
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan Data GAGAL" + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_Laboraturium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_Laboraturium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_Laboraturium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_Laboraturium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_Laboraturium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diagnosa_Penyakit;
    private javax.swing.JTextField Gejala_Penyakit;
    private javax.swing.JTextField ID_Pasien;
    private javax.swing.JTextField Kode_Obat;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_datalab;
    // End of variables declaration//GEN-END:variables
}
