/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author virgi
 */
public class Page_PaseinBaru extends javax.swing.JFrame {

    /**
     * Creates new form Page_PaseinBaru
     */
    DefaultTableModel model;
    
    public Page_PaseinBaru() {
        initComponents();
        String[] judul = {"ID Pasien", "Nama Pasien", "Umur Pasien", "Jenis Kelamin", "No Handphone", "Nama Dokter", "Poliklinik", "Alamat Pasien"};
        model = new DefaultTableModel(judul, 0);
        tbl_datapasien.setModel(model);
        tampilData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nama_Doktor = new javax.swing.JComboBox<>();
        ID_Pasien = new javax.swing.JTextField();
        Nama_Pasien = new javax.swing.JTextField();
        Umur_Pasien = new javax.swing.JTextField();
        PhoneNum_Pasien = new javax.swing.JTextField();
        JK_Pasien = new javax.swing.JComboBox<>();
        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datapasien = new javax.swing.JTable();
        btn_close = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Poli_Klinik = new javax.swing.JComboBox<>();
        btn_find = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat_Pasien = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Pengisian Data Pasien Baru");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Rumah Sakit Fakultas Teknik Universitas Indonesia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("ID Pasien                    :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setText("Nama Pasien               :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 207, -1));

        jLabel5.setText("Alamat Pasien             :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel6.setText("Umur Pasien               :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel7.setText("Jenis Kelamin              :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel8.setText("Nomor Handphone       :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel9.setText("Nama Doktor               :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Nama_Doktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih :", "Dr. Setya", "Dr. Budi", "Dr. Sakti", "Dr. Vina", "Dr. Bram" }));
        Nama_Doktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_DoktorActionPerformed(evt);
            }
        });
        getContentPane().add(Nama_Doktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 130, -1));
        getContentPane().add(ID_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 257, -1));
        getContentPane().add(Nama_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 330, -1));
        getContentPane().add(Umur_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 330, -1));
        getContentPane().add(PhoneNum_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 330, -1));

        JK_Pasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose :", "Laki Laki", "Perempuan" }));
        getContentPane().add(JK_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 132, -1));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, -1, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, -1, -1));

        tbl_datapasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datapasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datapasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datapasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, -1, 128));

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 830, -1, -1));

        jLabel10.setText("Poliklinik                     :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        Poli_Klinik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih :", "Poliklinik Penyakit Dalam", "Poliklinik Bedah", "Poliklinik Kebidanan dan Kandungan", "Poliklinik Anak", "Poliklinik Saraf", "Poliklinik Bedah Saraf", "Poliklinik Orthopaedi", "Poliklinik THT-KL", "Poliklinik Kulit dan Kelamin", "Poliklinik Kedokteran Jiwa", "Poliklinik Gigi dan Mulut", "Poliklinik Bedah Mulut" }));
        getContentPane().add(Poli_Klinik, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 130, -1));

        btn_find.setText("Cari");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });
        getContentPane().add(btn_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        Alamat_Pasien.setColumns(20);
        Alamat_Pasien.setRows(5);
        jScrollPane2.setViewportView(Alamat_Pasien);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 330, 177));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Icon/Icon Daftar Pasien.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "insert into data_pasien values(?,?,?,?,?,?,?,?)";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);

            statement.setString(1, ID_Pasien.getText());
            statement.setString(2, Nama_Pasien.getText());
            statement.setString(3, Alamat_Pasien.getText());
            statement.setString(4, Umur_Pasien.getText());
            statement.setString(5, (String) JK_Pasien.getSelectedItem());
            statement.setString(6, PhoneNum_Pasien.getText());
            statement.setString(7, (String) Nama_Doktor.getSelectedItem());
            statement.setString(7, (String) Poli_Klinik.getSelectedItem());
            statement.executeUpdate();
            tampilData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN", "informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN" + e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "update data_pasien set Nama_Pasien=?, Umur_Pasien=?, Jenis_Kelamin=?, No_Handphone=?, Nama_Doktor=?, Poliklinik=?, Alamat=? where ID_Pasien=?";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);

            statement.setString(1, Nama_Pasien.getText());
            statement.setString(2, Alamat_Pasien.getText());
            statement.setString(3, Umur_Pasien.getText());
            statement.setString(4, (String) JK_Pasien.getSelectedItem());
            statement.setString(5, PhoneNum_Pasien.getText());
            statement.setString(6, (String) Nama_Doktor.getSelectedItem());
            statement.setString(6, (String) Poli_Klinik.getSelectedItem());
            statement.setString(7, ID_Pasien.getText());

            statement.executeUpdate();
            tampilData();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH", "informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH" + e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        new Page_MedicalCheckUp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            String sql = "SELECT * FROM data_pasien WHERE ID_Pasien";
            java.sql.PreparedStatement statement = cn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery(sql);
            if (rs.next()){
                Nama_Pasien.setText(rs.getString(2));
                Umur_Pasien.setText(rs.getString(3));
                JK_Pasien.setSelectedItem(rs.getString(4));
                PhoneNum_Pasien.setText(rs.getString(5));
                Nama_Doktor.setSelectedItem(rs.getString(6));
                Poli_Klinik.setSelectedItem(rs.getString(7));
                Alamat_Pasien.setText(rs.getString(8));
                JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            }
            statement.close();
        }
        catch( SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int baris = tbl_datapasien.getSelectedRow();
        String ID_Pasien = model.getValueAt(baris, 0).toString();
        int Data = JOptionPane.showConfirmDialog(null, "Apakah anda ingin mengapus data ID Pasien : " + ID_Pasien + "?", "konfirmasi", JOptionPane.YES_NO_OPTION);

        if (Data == 0) {
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
                String sql = "delete from data_pasien where ID_Pasien ='" + ID_Pasien + "'";
                java.sql.PreparedStatement statement = cn.prepareStatement(sql);

                statement.executeUpdate();
                tampilData();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS", "informasi", JOptionPane.INFORMATION_MESSAGE);
                reset();

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DIHAPUS" + e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_datapasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datapasienMouseClicked
        // TODO add your handling code here:
        int i = tbl_datapasien.getSelectedRow();

        if (i > -1) {
            ID_Pasien.setText(model.getValueAt(i, 0).toString());
            Nama_Pasien.setText(model.getValueAt(i, 1).toString());
            Alamat_Pasien.setText(model.getValueAt(i, 2).toString());
            Umur_Pasien.setText(model.getValueAt(i, 3).toString());
            JK_Pasien.setSelectedItem(model.getValueAt(i, 4).toString());
            PhoneNum_Pasien.setText(model.getValueAt(i, 5).toString());
            Nama_Doktor.setSelectedItem(model.getValueAt(i, 6).toString());
            Poli_Klinik.setSelectedItem(model.getValueAt(i, 7).toString());
        }
    }//GEN-LAST:event_tbl_datapasienMouseClicked

    private void Nama_DoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_DoktorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_DoktorActionPerformed

     private void reset(){
        ID_Pasien.setText("");
        Nama_Pasien.setText("");
        Alamat_Pasien.setText("");
        Umur_Pasien.setText("");
        JK_Pasien.setSelectedItem("-PILIH-");
        PhoneNum_Pasien.setText("");
        Nama_Doktor.setSelectedItem("-PILIH-");
        Poli_Klinik.setSelectedItem("-PILIH-");
        
    }
    
    private void tampilData() {
        int row = tbl_datapasien.getRowCount();
        for (int a = 0; a < row; a++) {
            model.removeRow(0);
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM data_pasien");
            while (rs.next()) {
                String data[] = {rs.getString("ID_Pasien"), rs.getString("Nama_pasien"), rs.getString("Umur_Pasien"), rs.getString("Jenis_Kelamin"), rs.getString("No_Handphone"), rs.getString("Nama_Doktor"), rs.getString("Poliklinik"), rs.getString("Alamat")};
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan Data GAGAL" + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_PaseinBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_PaseinBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_PaseinBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_PaseinBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_PaseinBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat_Pasien;
    private javax.swing.JTextField ID_Pasien;
    private javax.swing.JComboBox<String> JK_Pasien;
    private javax.swing.JComboBox<String> Nama_Doktor;
    private javax.swing.JTextField Nama_Pasien;
    private javax.swing.JTextField PhoneNum_Pasien;
    private javax.swing.JComboBox<String> Poli_Klinik;
    private javax.swing.JTextField Umur_Pasien;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_datapasien;
    // End of variables declaration//GEN-END:variables
}
