
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author virgi
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        repass_field = new javax.swing.JPasswordField();
        password_field = new javax.swing.JPasswordField();
        firstname_field = new javax.swing.JTextField();
        lastname_field = new javax.swing.JTextField();
        username_field = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        btn_backlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat_field = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Pendaftaran Akun");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Rumah Sakit Fakultas Teknik Universitas Indonesia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 207, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Icon/logo-kesehatan.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 13, 118, 129));

        jLabel5.setText(" First Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 250, -1, -1));

        jLabel6.setText("Last Name :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 290, -1, -1));

        jLabel7.setText("Username :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 333, -1, -1));

        jLabel8.setText("Password :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 365, -1, -1));

        jLabel9.setText("Retype Password :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 405, -1, -1));

        jLabel10.setText("Alamat :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 437, -1, -1));
        getContentPane().add(repass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 402, 266, -1));
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 362, 266, -1));
        getContentPane().add(firstname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 247, 266, -1));
        getContentPane().add(lastname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 287, 266, -1));
        getContentPane().add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 327, 266, -1));

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 599, -1, -1));

        btn_register.setBackground(new java.awt.Color(102, 204, 255));
        btn_register.setText("REGISTER");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 599, -1, -1));

        btn_backlogin.setText("If Already have account, Click here to login");
        btn_backlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backloginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_backlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 637, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Icon/Icon CCIT FTUI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, 368, 139));

        alamat_field.setColumns(20);
        alamat_field.setRows(5);
        jScrollPane1.setViewportView(alamat_field);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 437, 266, 132));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backloginActionPerformed
        // TODO add your handling code here:
        Page_Login logIn = new Page_Login();
        logIn.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backloginActionPerformed
    
    public boolean checkUsername(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM data_users WHERE username =?";
        
        try{
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, username);
                
                rs = ps.executeQuery();
                
                if(rs.next())
                {
                    checkUser = true;
                }
              } catch (SQLException ex){
                  java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        return checkUser;
    }

      
    
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        String fname = username_field.getText();
        String lname = lastname_field.getText();
        String uname = username_field.getText();
        String pass = String.valueOf(password_field.getPassword());
        String re_pass = String.valueOf(repass_field.getPassword());
        String address = alamat_field.getText();
        
        if(uname.equals(""))
        {
        JOptionPane.showMessageDialog(null, "Add A Username");
        }
        
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Password");
        }
        
        else if(!pass.equals(re_pass))
        {
            JOptionPane.showMessageDialog(null, "Retype The Password Again");
        } 
        
        else if(checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null, "This Username Already Exist");
        }
      
        PreparedStatement ps;
        String query = "INSERT INTO data_users (Username, U_firstname, U_lastname, U_password, U_alamat) VALUE(?,?,?,?,?)";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1,fname);
            ps.setString(2, lname);
            ps.setString(3, uname);
            ps.setString(4, pass);
            ps.setString(5, address);
            
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "New User Add");
            }
        } catch (SQLException ex){
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        Page_Login logIn = new Page_Login();
        logIn.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_field;
    private javax.swing.JButton btn_backlogin;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField firstname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname_field;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JPasswordField repass_field;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
